"""Before-and-after table for a player-pool change (read-only).

  python scripts/compare_pools.py [--before slotpool_v1] [--after eligibility_v2]

Reads volume_efficiency_results_<version>.parquet for both versions and prints, for the markets present in BOTH, graded
rows, best-baseline error, model error, gain, 95% interval, seasons won and verdict -- then the markets that exist only
in the new version (the QB-rushing markets) on their own, with their pool sizes. Writes docs/pool_comparison_<after>.md.
Nothing is overwritten and nothing is re-run.
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import polars as pl  # noqa: E402

import config  # noqa: E402


def summary(version: str) -> pl.DataFrame:
    r = pl.read_parquet(config.result_path("volume_efficiency_results", version))
    s = r.filter(pl.col("table") == "summary")
    num = s.filter(pl.col("label").is_null()).pivot(on="metric", index="market", values="value")
    lab = s.filter(pl.col("label").is_not_null()).pivot(on="metric", index="market", values="label")
    return num.join(lab, on="market")


def fmt(df: pl.DataFrame, tag: str) -> pl.DataFrame:
    return df.select(
        "market", pl.col("n").cast(pl.Int64).alias(f"rows_{tag}"), pl.col("best_baseline").alias(f"best_{tag}"),
        pl.col("best_loss").round(4).alias(f"base_{tag}"), pl.col("model_loss").round(4).alias(f"model_{tag}"),
        pl.col("gain").round(4).alias(f"gain_{tag}"),
        pl.format("[{}, {}]", pl.col("ci_lo").round(3), pl.col("ci_hi").round(3)).alias(f"ci95_{tag}"),
        (pl.col("seasons_won").cast(pl.Int64).cast(pl.String) + "/" + pl.col("seasons_total").cast(pl.Int64).cast(pl.String)).alias(f"seasons_{tag}"),
        pl.col("verdict").alias(f"verdict_{tag}"))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--before", default="slotpool_v1")
    ap.add_argument("--after", default=config.ELIGIBLE_PLAYER_RULE["version"])
    a = ap.parse_args()
    b, n = summary(a.before), summary(a.after)
    order = list(config.MARKETS)
    both = [m for m in order if m in set(b["market"]) and m in set(n["market"])]
    only_new = [m for m in order if m in set(n["market"]) and m not in set(b["market"])]
    out = []
    with pl.Config(tbl_rows=40, tbl_cols=20, tbl_width_chars=260, fmt_str_lengths=24, tbl_hide_dataframe_shape=True):
        print(f"\nBEFORE ({a.before}) vs AFTER ({a.after}): volume x efficiency model vs best baseline, 2020-2024 walk-forward")
        print("rows = graded rows; base = best-baseline error (MAE; moneyline = Brier); gain = base - model (positive = model better)\n")
        for m in both:
            br, nr = b.filter(pl.col("market") == m), n.filter(pl.col("market") == m)
            line = fmt(br, "before").join(fmt(nr, "after"), on="market")
            out.append(line)
        t = pl.concat(out)
        print(t.select("market", "rows_before", "rows_after", "best_before", "best_after", "base_before", "base_after", "model_before", "model_after"))
        print(t.select("market", "gain_before", "gain_after", "ci95_before", "ci95_after", "seasons_before", "seasons_after", "verdict_before", "verdict_after"))
        changed = t.filter(pl.col("verdict_before") != pl.col("verdict_after"))["market"].to_list()
        print("\nverdict changed in:", changed or "none")
        if only_new:
            print("\nNEW markets (no before):")
            q = fmt(n.filter(pl.col("market").is_in(only_new)).sort("market"), "after")
            print(q)
    path = ROOT / "docs" / f"pool_comparison_{a.after}.md"
    path.parent.mkdir(exist_ok=True)

    def md_table(df):
        rows = [" | ".join(df.columns), " | ".join("---" for _ in df.columns)]
        rows += [" | ".join("" if v is None else str(v) for v in r) for r in df.iter_rows()]
        return "\n".join(f"| {r} |" for r in rows)

    md = [f"# Player-pool comparison: {a.before} -> {a.after}", "",
          "Generated by `scripts/compare_pools.py`. rows = graded rows; base = best-baseline error (MAE; moneyline = Brier); "
          "gain = base - model (positive = model better); CI = 95% bootstrap over season-weeks.", "",
          "## Markets present in both", "", md_table(t), ""]
    if only_new:
        md += ["## New markets (no before)", "", md_table(q), ""]
    path.write_text("\n".join(md))
    print(f"\nwrote {path.relative_to(ROOT)}")
